-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 17:35:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`book` ;

CREATE TABLE IF NOT EXISTS `library`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'DOSTEPNA',
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id` (`book_id` ASC) VISIBLE,
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE,
  INDEX `idx_status` (`status` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`user` ;

CREATE TABLE IF NOT EXISTS `library`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`order` ;

CREATE TABLE IF NOT EXISTS `library`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  `book_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`order_id`, `book_id`, `user_id`),
  UNIQUE INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `order_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`book_id`),
  CONSTRAINT `order_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`role` ;

CREATE TABLE IF NOT EXISTS `library`.`role` (
  `role_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`role_name`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`user_role` ;

CREATE TABLE IF NOT EXISTS `library`.`user_role` (
  `role_name` VARCHAR(45) NOT NULL DEFAULT 'user',
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_name`, `username`),
  INDEX `fk_role_has_user_role1_idx` (`role_name` ASC) VISIBLE,
  INDEX `fk_user_role_user_username_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_user_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `library`.`role` (`role_name`),
  CONSTRAINT `fk_user_role_user_username`
    FOREIGN KEY (`username`)
    REFERENCES `library`.`user` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


------defining roles
INSERT INTO role VALUES('user', 'add new order');
INSERT INTO role VALUES('admin', 'all privilegesuser_role');


------populating db with sample data
INSERT INTO library.book (first_name, last_name, title, isbn, status) 
	VALUES('Henryk', 'Sienkiewicz', 'W pustyni i w puszczy', '9782123456803', 'DOSTEPNA'),
	('Henryk', 'Sienkiewicz', 'Potop', '9980123456803', 'DOSTEPNA'),
	('Henryk', 'Sienkiewicz', 'Krzyżacy', '998673456803', 'WYPOZYCZONA'),
	('John', 'Haldon', 'Wojny Bizancjum', '928345456803', 'DOSTEPNA'),
	('Frank', 'Lepper', 'Wojna Partyjska Trajana', '900145456803', 'WYPOZYCZONA');